### PR TITLE
Major update, mainly for HTML5

### PR DESCRIPTION
**Pull request by rtonsing**
This is humbly supplied for you to use or not as you see fit.

Copied from DistributedProofreaders/ppcomp project, file /ppcomp/ppcomp.py

I have been comparing it to results from both PPWB and PPTools versions, and don't see any unexpected differences.

Changes:
    use html5parser.
    eliminate oe ligature transforms, treat same as ae.
    --css-bold option has default of '=',
    changed boilerplate removal to latest format
    added super/subscript conversions (`<sup>1</sup>` or ^1 to '¹'.

I did a LOT of rewriting, mainly to make each functionality accessible for unit testing, partly code "cleanup" or just adapting to my style so I could understand it better.

--extract-footnotes needs work, but it shouldn't be any worse.

### CODE REVIEW

**Comment by bibimbop** [comment]
That's a lot of changes. I just can't review it. But as it's probably useful, I leave that PR up for posterity.

**Comment by rtonsing** [comment]
Cancelling for now, if there is future interest the latest version should be pulled from DistributedProofreaders/ppcomp.

**Comment by tangledhelix** [comment]
@rtonsing I talked to @bibimbop recently, and I'm going to take over the pptools project. I have a fork now at [tangledhelix/pptools](https://github.com/tangledhelix/pptools) if you would like to re-issue the PR there.

**Comment by rtonsing** [comment]
That's great! I know there are people that prefer the way pptools works. I'm working on a fix for footnotes extraction, I will do a PR then.

**Pull request closed without merging**
